name: Build Python App

on:
  workflow_call:
    inputs:
      python-version:
        description: The version of Python to be used
        type: string
        default: 3.10.x

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: .

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v3
      with:
        python-version: ${{ inputs.python-version }}
        cache: 'pip'
        
    - name: Install dependencies
      run: pip install -t python -r requirements.txt
    - run: tree    
    - name: Upload a Build Artifact
      uses: asbaba-corp/pipelines/.github/actions/upload-artifact@main
      with:
        name: build-${{ github.event.number }}
        path: dist
        if-no-files-found: error
