name: Pull Request Check

on: workflow_call


jobs:
  build:
    name: Nodejs
    uses: ./.github/workflows/build-nodejs.yml
  plan:
    needs: [build]
    uses: ./.github/workflows/terraform-plan.yml
    secrets: inherit
