name: Pull Request Check

on: 
  workflow_call:
    inputs:
      module:
        type: string
        required: true


jobs:
  build:
    name: Python
    uses: ./.github/workflows/build-python.yml
  plan:
    needs: [build]
    uses: ./.github/workflows/terraform-plan.yml
    secrets: inherit
    with:
      module: ${{inputs.module}}
