name: Pull Request Check

on:
  pull_request:
    types: [opened, reopened, edited, synchronize]

jobs:
  build:
    name: Nodejs
    uses: ./.github/workflows/build/build-nodejs.yml
    with:
      runs-on: "ubuntu-latest"
  plan:
    needs: [build]
    uses: ./.github/workflows/terraform/terraform-plan.yml
    with:
      config_directory: "."
    secrets: inherit