name: Pull Request Check

on:
  pull_request:
    types: [opened, reopened, edited, synchronize]

jobs:
  build:
    name: Nodejs
    uses: ./.github/workflows/build-nodejs.yml
  plan:
    needs: [build]
    uses: ./.github/workflows/terraform-plan.yml
    secrets: inherit
