name: Release Workflow

on: workflow_call

jobs:
  build:
    name: Build node
    uses: ./.github/workflows/build-nodejs.yml
    with:
      runs-on: "ubuntu-latest"
  terraform-plan:
    name: Terraform plan
    needs: [build]
    uses: ./.github/workflows/terraform-plan.yml
    with:
      config_directory: "/terraform"
    secrets: inherit
  terraform-apply:
    name: Terraform apply
    needs: [terraform-plan]
    uses: ./.github/workflows/terraform-apply.yml 
    secrets: inherit