name: Release Dev Workflow

on: workflow_call

jobs:
  nodejs:
    name: Nodejs
    uses: ./.github/workflows/build-nodejs.yml
    if: inputs.repository_language == 'nodejs'
    
  python:
    name: Python
    uses: ./.github/workflows/build-python.yml
    if: inputs.repository_language == 'python'
    
  terraform-plan:
    needs: ${{ inputs.repository_language }}
    uses: ./.github/workflows/terraform-plan.yml
    with:
      config_directory: "/terraform"
    secrets: inherit
    
  terraform-apply:
    needs: [terraform-plan]
    uses: ./.github/workflows/terraform-apply.yml 
    secrets: inherit
