name: Release Dev Workflow

on: 
  workflow_call:
    inputs:
      repository_language:
        type: string
        required: true
      config_directory:
        type: string
        required: false
        default: .

jobs:
  nodejs:
    name: Nodejs
    uses: ./.github/workflows/build-nodejs.yml
    if: inputs.repository_language == 'nodejs'
    
  python:
    name: Python
    uses: ./.github/workflows/build-python.yml
    if: inputs.repository_language == 'python'

  check-success:
    runs-on: ubuntu-latest
    needs: [nodejs, python]
    if: |
      always() && 
      (needs.nodejs.result == 'success' || needs.nodejs.result == 'skipped') && 
      (needs.python.result == 'success' || needs.python.result == 'skipped') && 
      !(needs.nodejs.result == 'skipped' && needs.python.result == 'skipped')
    steps:
      - run: echo Check success
    
  terraform-plan:
    name: Terraform
    needs: [check-success]
    uses: ./.github/workflows/terraform-plan.yml
    with:
      config_directory: ${{inputs.config_directory}}
    secrets: inherit
    
  terraform-apply:
    name: Provision
    needs: [terraform-plan]
    if: needs.terraform-plan.result == 'success'
    uses: ./.github/workflows/terraform-apply.yml 
    secrets: inherit
