name: Release Dev Workflow

on: 
  workflow_call:
    inputs:
      repository_language:
        type: string
        required: true
      config_directory:
        type: string
        required: false
        default: .

jobs:
  nodejs:
    name: Nodejs
    uses: ./.github/workflows/build-nodejs.yml
    if: inputs.repository_language == 'nodejs'
    
  python:
    name: Python
    uses: ./.github/workflows/build-python.yml
    if: inputs.repository_language == 'python'
    
  terraform-plan:
    name: Terraform
    needs: [nodejs, python]
    if: ${{ always() }}
    uses: ./.github/workflows/terraform-plan.yml
    with:
      config_directory: ${{inputs.config_directory}}
    secrets: inherit
    
  terraform-apply:
    name: Provision
    needs: [terraform-plan]
    if: ${{ always() }}
    uses: ./.github/workflows/terraform-apply.yml 
    secrets: inherit
