name: Release Dev Workflow

on:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  build:
    name: Nodejs
    uses: ./.github/workflows/build/build-nodejs.yml
    with:
      runs-on: "ubuntu-latest"
  terraform-plan:
    needs: [build]
    uses: ./.github/workflows/terraform/terraform-plan.yml
    with:
      config_directory: "/terraform"
    secrets: inherit
  terraform-apply:
    needs: [terraform-plan]
    uses: ./.github/workflows/terraform/terraform-apply.yml 
    secrets: inherit