name: "Terraform Apply"

on:
  workflow_call:
    inputs:
      terraform-version:
        default: 1.5.0
        type: string
        

jobs:
  terraform:
    name: "Apply"
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
          terraform_version: ${{inputs.terraform-version}}
          
      - name: Download artifact
        uses: asbaba-corp/pipelines/.github/actions/download-artifact@main
        continue-on-error: true
        with:
          name: build-${{ github.event.number }}
          path: dis
         
      - name: Provision infra
        continue-on-error: true
        run: |
          terraform init && terraform apply -input=false -auto-approve -no-color
